### ISSUE TITLE
UniRep fails on empty sequences

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#117]
```
Traceback (most recent call last):                                                                                                                                                            
  File "/mnt/project/seqvec-search/bio_embeddings/tests/test_hypothesis_bio.py", line 54, in test_foo                                                                                         
    embedding = cached_embedder.embed(sequence)                                                                                                                                               
  File "/mnt/project/seqvec-search/bio_embeddings/bio_embeddings/embed/unirep_embedder.py", line 45, in embed                                                                                 
    embedded_seqs = get_embeddings([sequence])                                                                                                                                                
  File "/mnt/project/seqvec-search/.venv/lib/python3.8/site-packages/jax_unirep/utils.py", line 200, in get_embeddings                                                                        
    seq_embeddings = [get_embedding(s, embeddings) for s in sequences]                                                                                                                        
  File "/mnt/project/seqvec-search/.venv/lib/python3.8/site-packages/jax_unirep/utils.py", line 200, in <listcomp>                                                                            
    seq_embeddings = [get_embedding(s, embeddings) for s in sequences]                                                                                                                        
  File "/mnt/project/seqvec-search/.venv/lib/python3.8/site-packages/jax_unirep/utils.py", line 167, in get_embedding                                                                         
    raise SequenceLengthsError("Sequence must be at least of length one.")                                                                                                                    
jax_unirep.errors.SequenceLengthsError: Sequence must be at least of length one.      
```

**Comment by sacdallago** [comment]
I think this is ok, the only frustrating thing is if this happens in the pipeline: you embed all sequences up to the last one(s) which are empty. I suggest the same as https://github.com/sacdallago/bio_embeddings/issues/120#issuecomment-811816065 , but reverse: check last entry in mapping file, if L < 1 throw the exception (the same they throw, for all that matters :) or use on of ours, doesn't matter).
