### ISSUE TITLE
webserver worker failing on no flask?

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#197]
```
www-data@45cda68b644f:/app$ /app/.venv/bin/python /app/.venv/bin/celery worker -A webserver.celery_worker.task_keeper --loglevel=WARNING --pool=solo -Q prott5 -n prott5_worker_2
Traceback (most recent call last):
  File "/app/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 32, in <module>
    from flask import (  # type: ignore
  File "/app/.venv/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/app/.venv/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/app/.venv/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/app/.venv/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/app/.venv/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/app/.venv/lib/python3.8/site-packages/markupsafe/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/app/.venv/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/base.py", line 289, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/base.py", line 509, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/base.py", line 531, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/app/.venv/lib/python3.8/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/app/.venv/lib/python3.8/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/app/.venv/lib/python3.8/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/app/.venv/lib/python3.8/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/webserver/celery_worker.py", line 1, in <module>
    from webserver.tasks import task_keeper
  File "/app/webserver/tasks/__init__.py", line 1, in <module>
    from webserver.utilities.configuration import configuration
  File "/app/webserver/utilities/configuration.py", line 6, in <module>
    from sentry_sdk.integrations.flask import FlaskIntegration
  File "/app/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/flask.py", line 44, in <module>
    raise DidNotEnable("Flask is not installed")
sentry_sdk.integrations.DidNotEnable: Flask is not installed
```

**Comment by sacdallago** [comment]
Outdated version of flask may be cause (https://github.com/pallets/markupsafe/issues/284). Should be fixed with 0b97edd4f82fcb7ffe12099aedc1e55a4dd9a503
