### ISSUE TITLE
Protocol esm: UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by wenyuhaokikika** [sacdallago/bio_embeddings#204]
## Metadata
|key|value|
|--|--|
|**version**|0.2.2|
|**cuda**|True|

## Parameter
|key|value|
|--|--|
type|embed
protocol|esm
reduce|True

## Traceback
```
Traceback (most recent call last):
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/bio_embeddings/utilities/pipeline.py", line 284, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/bio_embeddings/embed/pipeline.py", line 400, in run
    embedder: EmbedderInterface = embedder_class(**result_kwargs)
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/bio_embeddings/embed/esm_embedder.py", line 39, in __init__
    model, alphabet = load_model_and_alphabet_local(self._options["model_file"])
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/bio_embeddings/embed/esm_embedder.py", line 22, in load_model_and_alphabet_local
    model_data = torch.load(model_location, map_location="cpu")
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data/wenyuhao/anaconda3/envs/fastText/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
```

**Comment by wenyuhaokikika** [comment]
remove model and download again.
https://github.com/danielgatis/rembg/issues/154#issuecomment-943182349
