### ISSUE TITLE
Protocol prottrans_t5_xl_u50: URLError: <urlopen error [Errno 113] No route to host>

### ISSUE THREAD

**Issue by Azai-yx** [sacdallago/bio_embeddings#223]
## Metadata
|key|value|
|--|--|
|**version**|0.2.2|
|**cuda**|True|

## Parameter
|key|value|
|--|--|
type|embed
protocol|prottrans_t5_xl_u50
half_precision_model|True
half_precision|True
simple_remapping|True

## Traceback
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/site-packages/bio_embeddings/utilities/pipeline.py", line 284, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/site-packages/bio_embeddings/embed/pipeline.py", line 400, in run
    embedder: EmbedderInterface = embedder_class(**result_kwargs)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/site-packages/bio_embeddings/embed/prottrans_t5_embedder.py", line 55, in __init__
    super().__init__(**kwargs)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/site-packages/bio_embeddings/embed/embedder_interfaces.py", line 59, in __init__
    self._options[directory] = get_model_directories_from_zip(
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/site-packages/bio_embeddings/utilities/remote_file_retriever.py", line 78, in get_model_directories_from_zip
    with request.urlopen(req) as response, open(file_name, 'wb') as outfile:
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/ubuntu/anaconda3/envs/bio_emb/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>
```

**Comment by Azai-yx** [comment]
hello there. I recently need to embed 13-aa-long peptides to do a regression task. I am trying use light attention example config, and got this error reported. 
A further concern is that I am confused if this pretrain model is suitable for embed peptides instead of a long protein sequences. Theoratically,  I assume peptides could also be embedded right?
