### ISSUE TITLE
Error during first step - greenlet size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by igwill** [sacdallago/bio_embeddings#233]
Hi, I am encountering an error that looks similar to https://github.com/sacdallago/bio_embeddings/issues/184, but flagging greenlet rather than numpy.
My end goal is to run some protein-protein interaction predictions using TAGPPI, which takes SeqVec embeddings as part of its input.

I've just pip installed bio-embeddings[all], and am trying to embed via seqvec.
Using either a config.yml specifying seqvec or "from bio_embeddings.embed import SeqVecEmbedder" I get the following error, any thoughts on getting this running?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/site-packages/bio_embeddings/__init__.py", line 12, in <module>
    import bio_embeddings.embed
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/site-packages/bio_embeddings/embed/__init__.py", line 132, in <module>
    from bio_embeddings.embed.seqvec_embedder import SeqVecEmbedder
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/site-packages/bio_embeddings/embed/seqvec_embedder.py", line 5, in <module>
    from allennlp.commands.elmo import ElmoEmbedder
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/site-packages/allennlp/commands/__init__.py", line 8, in <module>
    from allennlp.commands.configure import Configure
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/site-packages/allennlp/commands/configure.py", line 23, in <module>
    from gevent.pywsgi import WSGIServer
  File "/home/iwill/.local/lib/python3.8/site-packages/gevent/__init__.py", line 87, in <module>
    from gevent._hub_local import get_hub
  File "/home/iwill/.local/lib/python3.8/site-packages/gevent/_hub_local.py", line 101, in <module>
    import_c_accel(globals(), 'gevent.__hub_local')
  File "/home/iwill/.local/lib/python3.8/site-packages/gevent/_util.py", line 105, in import_c_accel
    mod = importlib.import_module(cname)
  File "/home/iwill/my-envs/bio-embeddings/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "src/gevent/__greenlet_primitives.pxd", line 12, in init gevent.__hub_local
ValueError: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152 from C header, got 40 from PyObject
```
My conda environment:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   1.4.0                    pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alabaster                 0.7.13                   pypi_0    pypi
alembic                   1.10.3                   pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
atomicwrites              1.4.1                    pypi_0    pypi
attrs                     22.2.0                   pypi_0    pypi
babel                     2.12.1                   pypi_0    pypi
binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
binutils_linux-64         2.39                h5fc0e48_12    conda-forge
bio-embeddings            0.2.2                    pypi_0    pypi
bio-embeddings-allennlp   0.9.2                    pypi_0    pypi
bio-embeddings-bepler     0.0.1                    pypi_0    pypi
bio-embeddings-cpcprot    0.0.1                    pypi_0    pypi
bio-embeddings-deepblast  0.1.0                    pypi_0    pypi
bio-embeddings-plus       0.1.1                    pypi_0    pypi
bio-embeddings-tape-proteins 0.5                      pypi_0    pypi
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cmaes                     0.9.1                    pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
conllu                    4.4                      pypi_0    pypi
contourpy                 1.0.7                    pypi_0    pypi
cxx-compiler              1.0.0                hf484d3e_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
exceptiongroup            1.1.1                    pypi_0    pypi
fair-esm                  0.4.0                    pypi_0    pypi
filelock                  3.11.0                   pypi_0    pypi
flask                     2.2.3                    pypi_0    pypi
fonttools                 4.39.3                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.4.0                 pypi_0    pypi
gcc                       12.2.0              h26027b1_12    conda-forge
gcc_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
gcc_linux-64              12.2.0              h4798a0e_12    conda-forge
greenlet                  2.0.2                    pypi_0    pypi
gxx_impl_linux-64         12.2.0              hcc96c02_19    conda-forge
gxx_linux-64              12.2.0              hb41e900_12    conda-forge
huggingface-hub           0.13.4                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
importlib-resources       5.12.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jax                       0.1.77                   pypi_0    pypi
jax-unirep                1.0.3                    pypi_0    pypi
jaxlib                    0.4.7                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonnet                   0.19.1                   pypi_0    pypi
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libffi                    3.3                  he6710b0_2
libgcc-devel_linux-64     12.2.0              h3b97bd3_19    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libsanitizer              12.2.0              h46fd767_19    conda-forge
libstdcxx-devel_linux-64  12.2.0              h3b97bd3_19    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
lightning-utilities       0.8.0                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
lmdb                      1.4.1                    pypi_0    pypi
mako                      1.2.4                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
ml-dtypes                 0.0.4                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nltk                      3.8.1                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
openssl                   1.1.1t               h0b41bf4_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    3.1.1                    pypi_0    pypi
packaging                 23.0                     pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       23.0.1           py38h06a4308_0
pluggy                    1.0.0                    pypi_0    pypi
pygments                  2.15.0                   pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pytest                    7.3.0                    pypi_0    pypi
python                    3.8.3                hcff3b4d_2
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-lightning         1.8.6                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
requests                  2.28.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py38h06a4308_0
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    6.1.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                2.0.9                    pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0
sysroot_linux-64          2.12                he073ed8_15    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.13.3                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     1.9.1                    pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.27.4                   pypi_0    pypi
typing-extensions         4.5.0                    pypi_0    pypi
unidecode                 1.3.6                    pypi_0    pypi
urllib3                   1.26.15                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
werkzeug                  2.2.3                    pypi_0    pypi
wheel                     0.38.4           py38h06a4308_0
word2number               1.1                      pypi_0    pypi
xz                        5.2.10               h5eee18b_1
yarl                      1.8.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0
```

Thank you!

**Comment by igwill** [comment]
For those with a similar problem seeking to use SeqVec, I was able to get stand-alone SeqVec (https://github.com/rostlab/SeqVec) to run in a python3.6/greenlet0.4.15 environment.
