### ISSUE TITLE
Protocol prottrans_t5_xl_u50: PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpk7e1m0jg'

### ISSUE THREAD

**Issue by jbattjes** [sacdallago/bio_embeddings#238]
## Metadata
|key|value|
|--|--|
|**version**|0.2.2|
|**cuda**|False|

## Parameter
|key|value|
|--|--|
type|embed
protocol|prottrans_t5_xl_u50
half_precision_model|True
half_precision|True

## Traceback
```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bio_embeddings\utilities\pipeline.py", line 284, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bio_embeddings\embed\pipeline.py", line 400, in run
    embedder: EmbedderInterface = embedder_class(**result_kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bio_embeddings\embed\prottrans_t5_embedder.py", line 55, in __init__
    super().__init__(**kwargs)
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bio_embeddings\embed\embedder_interfaces.py", line 60, in __init__
    model=self.name, directory=directory
  File "c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bio_embeddings\utilities\remote_file_retriever.py", line 78, in get_model_directories_from_zip
    with request.urlopen(req) as response, open(file_name, 'wb') as outfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpk7e1m0jg'
```

**Comment by jbattjes** [comment]
Hi, could someone help me on this error? Cannot seem to solve it by myself. This is where it goes wrong:

 INFO Downloading model_folder_zip for prottrans_t5_xl_u50 and storing in 'C:\Users\user\AppData\Local\Temp\tmpxbik9_km'.

I do have administrator rights yet I cannot do this.
