### ISSUE TITLE
Protocol esm1b: HTTPError: HTTP Error 406: Not Acceptable

### ISSUE THREAD

**Issue by ragunyrasta** [sacdallago/bio_embeddings#248]
## Metadata
|key|value|
|--|--|
|**version**|0.1.6|
|**cuda**|True|

## Parameter
|key|value|
|--|--|
type|embed
protocol|esm1b
reduce|True

## Traceback
```
Traceback (most recent call last):
  File "/app/bio_embeddings/utilities/pipeline.py", line 262, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/app/bio_embeddings/embed/pipeline.py", line 335, in run
    result_kwargs[file] = get_model_file(model=embedder_class.name, file=file)
  File "/app/bio_embeddings/utilities/remote_file_retriever.py", line 109, in get_model_file
    request.urlretrieve(url, filename=cache_path, reporthook=t.update_to)
  File "/usr/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call

**Comment by ragunyrasta** [comment]
I get the above error. It appears that the model weights may not be available at the expected locations(this happens for seqvec too). Is there a new location instead?
