### ISSUE TITLE
General purpose embedders not loading 

### ISSUE THREAD

**Issue by gregmcinnes** [sacdallago/bio_embeddings#43]
I'm trying to use the embedders within a python script but they are not loading.  I've tried just the example code from the README, but this is what I get

    >>> from bio_embeddings.embed import SeqVecEmbedder
    >>> embedder = SeqVecEmbedder()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/site-packages/bio_embeddings/embed/seqvec_embedder.py", line 48, in __init__
        self._weights_file = self._options["weights_file"]
    KeyError: 'weights_file'

I also tried BertEmbedder but I get a different error

    >>> from bio_embeddings.embed import *
    >>> embedder = BertEmbedder()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/site-packages/bio_embeddings/embed/bert_embedder.py", line 29, in __init__
        self.model = BertModel.from_pretrained(self._model_directory)
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/site-packages/transformers/modeling_utils.py", line 587, in from_pretrained
        **kwargs,
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/site-packages/transformers/configuration_utils.py", line 201, in from_pretrained
        config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/site-packages/transformers/configuration_utils.py", line 224, in get_config_dict
        if os.path.isdir(pretrained_model_name_or_path):
      File "/share/PI/rbaltman/gmcinnes/bin/miniconda3/envs/bioembeddings/lib/python3.6/genericpath.py", line 42, in isdir
        st = os.stat(s)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

I installed the repo via github in a fresh miniconda environment two days ago.

**Comment by sacdallago** [comment]
Hi @gregmcinnes , thanks for using the pipeline.

The current develop version is not stable, I would suggest you to install the pip version if you want a stable relase.

What you are experiencing with both embedders is that the automatic download of the model files is not fully fallback proof. @konstin is working on refactoring that code. You have two options:

- Install the stable version (`pip uninstall bio_embeddings && pip install bio_embeddings`). This will only give you SeqVec, as Bert is currently being added and will be stable in release `v0.1.4`
- Provide the weights and options file yourself (this is anyway more efficient/better if you plan on running the pipeline multiple times, as IO is expensive):
  - Download them from here: 
     - SeqVec: http://maintenance.dallago.us/public/embeddings/embedding_models/seqvec/
     - Bert: http://maintenance.dallago.us/public/embeddings/embedding_models/bert/
  - Then initialize the model like:
     - SeqVec: Simply link the files in the constructor: `SeqVecEmbedder(weights_file="/path/to/file", options_file="/path/to/file")`
    - Bert: unzip the folder, then `BertEmbedder(model_directory="/path/to/model/directory")`


Let me know if anything is still unclear or if you can't solve the issue with the instructions above :)

**Comment by sacdallago** [comment]
Reopening for @konstin to keep in mind :)

**Comment by gregmcinnes** [comment]
This worked great.  Thanks!  This seems like a very useful project.

**Comment by konstin** [comment]
The code that failed in the initial report now works with current `develop`.
