### ISSUE TITLE
Document when you can reduce and/or discard_per_amino_acid_embeddings

### ISSUE THREAD

**Issue by konstin** [sacdallago/bio_embeddings#55]
I could not find any documentation on which stages need per-residue and which need per-protein embeddings, and thereby whether it's possible to use `reduce: true` with these stages or not.

**Comment by konstin** [comment]
The following pipeline currently fails with an unhelpful error, which commenting out `discard_per_amino_acid_embeddings: true` fixes: 

```yaml
global:
  sequences_file: fasta.fa
  prefix: simple
seqvec_embeddings:
  type: embed
  protocol: seqvec
  reduce: True
  #discard_per_amino_acid_embeddings: True
  weights_file: /mnt/nfs/models/seqvec/weights_file
  options_file: /mnt/nfs/models/seqvec/options_file
annotations_from_seqvec:
  type: extract
  protocol: seqvec_from_publication
  depends_on: seqvec_embeddings
```

Output:

```
 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                   | 4/5 [00:03<00:00,  1.24it/s]
Traceback (most recent call last):
  File "/home/kschuetze/bio_embeddings/.venv/bin/bio_embeddings", line 33, in <module>
    sys.exit(load_entry_point('bio-embeddings', 'console_scripts', 'bio_embeddings')())
  File "/home/kschuetze/bio_embeddings/bio_embeddings/utilities/cli.py", line 24, in main
    parse_config_file_and_execute_run(arguments.config_path[0], overwrite=arguments.overwrite)
  File "/home/kschuetze/bio_embeddings/bio_embeddings/utilities/pipeline.py", line 202, in parse_config_file_and_execute_run
    execute_pipeline_from_config(config, **kwargs)
  File "/home/kschuetze/bio_embeddings/bio_embeddings/utilities/pipeline.py", line 169, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/home/kschuetze/bio_embeddings/bio_embeddings/extract/pipeline.py", line 158, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/home/kschuetze/bio_embeddings/bio_embeddings/extract/pipeline.py", line 31, in seqvec_from_publication
    return predict_annotations_using_basic_models("seqvec_from_publication", **kwargs)
  File "/home/kschuetze/bio_embeddings/bio_embeddings/extract/pipeline.py", line 48, in predict_annotations_using_basic_models
    check_required(kwargs, ['embeddings_file', 'mapping_file', 'remapped_sequences_file'])
  File "/home/kschuetze/bio_embeddings/bio_embeddings/utilities/helpers.py", line 32, in check_required
    ", ".join(missing), params
bio_embeddings.utilities.exceptions.MissingParameterError: Missing required parameters: embeddings_file 
Given: {'sequences_file': 'simple/sequences_file.fasta', 'prefix': 'simple', 'simple_remapping': False, 'mapping_file': 'simple/mapping_file.csv', 'remapped_sequences_file': 'simple/remapped_sequences_file.fasta', 'type': 'extract', 'protocol': 'seqvec_from_publication', 'reduce': True, 'discard_per_amino_acid_embeddings': True, 'weights_file': '/mnt/nfs/models/seqvec/weights_file', 'options_file': '/mnt/nfs/models/seqvec/options_file', 'stage_name': 'annotations_from_seqvec', 'start_time': '2020-09-05 22:24:30.492982+02:00', 'max_amino_acids': 15000, 'reduced_embeddings_file': 'simple/seqvec_embeddings/reduced_embeddings_file.h5', 'end_time': '2020-09-05 22:24:30.490852+02:00', 'elapsed_time': '0:00:26.489258', 'depends_on': 'seqvec_embeddings'}
```

**Comment by sacdallago** [comment]
Documenting this extensively is hard.

I tried to address parts of this textually via the updated examples README in PR 42 on GitLab.

The solution to this is to read the first few lines of each protocol (in the code). There, neccessary files (and parameters) are `check_required`. This is also why that's one of the first lines: fail soon and fix problems before wasting someone's day.

P.S.: also documented in the `parameters_blueprint.yml` file!
