### ISSUE TITLE
New CUDA error signatures when OOM

### ISSUE THREAD

**Issue by sacdallago** [sacdallago/bio_embeddings#74]
On oculus, just now:

```
Traceback (most recent call last):
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/embedder_interfaces.py", line 171, in embed_batch
    yield from self._embed_batch_impl(batch, self._model)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/prottrans_bert_base_embedder.py", line 48, in _embed_batch_impl
    input_ids=tokenized_sequences, attention_mask=attention_mask
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 841, in forward
    return_dict=return_dict,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 482, in forward
    output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 402, in forward
    output_attentions=output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 339, in forward
    output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 258, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 70.34 GiB (GPU 0; 7.93 GiB total capacity; 2.35 GiB already allocated; 3.43 GiB free; 2.37 GiB reserved in total by PyTorch)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chdallago/miniconda3/envs/bio_embeddings/bin/bio_embeddings", line 8, in <module>
    sys.exit(main())
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/utilities/cli.py", line 24, in main
    parse_config_file_and_execute_run(arguments.config_path[0], overwrite=arguments.overwrite)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/utilities/pipeline.py", line 208, in parse_config_file_and_execute_run
    execute_pipeline_from_config(config, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/utilities/pipeline.py", line 175, in execute_pipeline_from_config
    stage_output_parameters = stage_runnable(**stage_parameters)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/pipeline.py", line 274, in run
    return PROTOCOLS[kwargs["protocol"]](**kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/pipeline.py", line 217, in prottrans_bert_bfd
    return transformer(ProtTransBertBFDEmbedder, 6024, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/pipeline.py", line 209, in transformer
    return embed_and_write_batched(embedder, file_manager, result_kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/pipeline.py", line 165, in embed_and_write_batched
    mapping_file.index, tqdm(embedding_generator, total=len(mapping_file))
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/embedder_interfaces.py", line 110, in embed_many
    yield from self.embed_batch([sequence])
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/embedder_interfaces.py", line 179, in embed_batch
    yield from self._embed_batch_impl(batch, self._get_fallback_model())
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/bio_embeddings/embed/prottrans_bert_base_embedder.py", line 48, in _embed_batch_impl
    input_ids=tokenized_sequences, attention_mask=attention_mask
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 841, in forward
    return_dict=return_dict,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 482, in forward
    output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 402, in forward
    output_attentions=output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 339, in forward
    output_attentions,
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chdallago/miniconda3/envs/bio_embeddings/lib/python3.7/site-packages/transformers/modeling_bert.py", line 259, in forward
    attention_scores = attention_scores / math.sqrt(self.attention_head_size)
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 75523833856 bytes. Error code 12 (Cannot allocate memory)
```

Not sure. I had the api.embed.protein.properties worker running in parallel, and apparently that one also suffered from being squeezed in... But yeah, just logging this for now, to look at some time in the future...

**Comment by sacdallago** [comment]
Didn't happen again, closing for now
